name: layout
description: >
  Sample app from "Building Layouts", https://flutter.io/docs/development/ui/layout.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^0.13.5
  video_player: ^2.1.12
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  floating_bottom_navigation_bar: ^1.5.2
  vibration: ^1.7.5
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16



flutter:
  uses-material-design: true
  assets:
    - images/lake.jpg
    - images/flutter2.png

flutter_native_splash:
  color: "#ffffff"
  image: images/flutter.png